Cu 86bx0njw8/be paginate upcoming activities endpoint return 5 items per page starting from most recent
Ajo-Savings-Project/ajo-savings pull request #111
Opened 2024-02-09 17:55 UTC by Don-christo

**Description of PR**

Paginated upcoming activities endpoint.

How to test:
- Add dummy data to your local db using the `createGroup` function. With the data you've created, you can use them to test the pagination function.

---

Please check all that apply.

#### Checklist:

- [x] Rebased with master
- [x] PR Description provided
- [x] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [x] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_

2024-02-09 17:55 UTC, KristofaJosh commented
Task linked: [CU-86bx0njw8 BE-paginate upcoming Activities endpoint. Return 5 items per page starting from most recent](https://app.clickup.com/t/86bx0njw8)

2024-02-10 18:07 UTC, pelzman submitted a review, later dismissed
Weldone IK

2024-02-13 18:34 UTC, KristofaJosh requested changes

2024-02-13 18:34 UTC, KristofaJosh commented on apps/server/src/controllers/userControllers/getUpcomingActivities.ts
I think you should prefer this approach with sequelize:

we can discuss this

```
...
const offset = (page - 1) * pageSize;
const limit = pageSize;

try {
     const results = await ModelName.findAndCountAll({ offset,   limit, order: [['createdAt', 'DESC']]});
     return {
            totalItems: results.count,
            totalPages: Math.ceil(results.count / pageSize),
            currentPage: page,
            pageSize: limit,
            data: results.rows,
        };
```

2024-02-13 18:34 UTC, KristofaJosh commented on apps/server/src/controllers/userControllers/userUpdateKyc.ts
> +    let _proof_of_address_doc =
This shouldn't be here

2024-02-15 10:51 UTC, Don-christo commented on apps/server/src/controllers/userControllers/userUpdateKyc.ts
> +    let _proof_of_address_doc =
You mean the file??

2024-02-15 12:16 UTC, KristofaJosh requested changes

2024-02-15 12:16 UTC, KristofaJosh commented on apps/server/src/controllers/userControllers/getUserProfileDetails.ts
not related to this ticket

2024-02-15 12:16 UTC, KristofaJosh commented on apps/server/src/controllers/userControllers/getUpcomingActivities.ts
> +        .join('&')
Use this:

https://www.npmjs.com/package/query-string

2024-02-15 12:16 UTC, KristofaJosh commented on apps/server/src/controllers/userControllers/getUpcomingActivities.ts
re check this and make the necessary fixes, given the new package I have shared with you


Good job so far

2024-02-15 14:25 UTC, KristofaJosh approved these changes

2024-02-15 14:31 UTC, KristofaJosh submitted a review, later dismissed

2024-02-15 14:37 UTC, KristofaJosh approved these changes

2024-02-15 20:19 UTC, merged