update create explore group view
Ajo-Savings-Project/ajo-savings pull request #112
Opened 2024-02-10 10:45 UTC by Elyzsium

**Description of PR**

create explore group view

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_

2024-02-10 10:45 UTC, KristofaJosh commented
Task linked: [CU-86bwt2ybt Create explore group view](https://app.clickup.com/t/86bwt2ybt)

2024-02-12 08:43 UTC, pelzman reviewed
![image](https://github.com/Ajo-Savings-Project/ajo-savings/assets/107943338/406e2545-0991-4656-9df1-cd9a1fa6df67)

you can make the table a component and pass the necessary parameters, this is because the table would still be re-use on another card, just to prevent repeating yourself

for styling
styling mobile view first would have saved you some stress and reduced your lines of code..

the image got too small on the small screen , adjust

2024-02-21 10:08 UTC, pelzman reviewed
Note: if you are doing mobile first, your width would be 100%

and besides… this your css is a bit long , it needs refactoring

2024-02-22 04:37 UTC, pelzman reviewed
![image](https://github.com/Ajo-Savings-Project/ajo-savings/assets/107943338/2875359b-7a41-4456-b105-ff5a4c1abdb1)

for the table - try and use divs instead of the table tag
read up on grid-template-area on https://www.youtube.com/watch?v=Ny7LkAt4btI&t=513s.   and also check the way i implemented the table on transacton page as a guide.

2024-02-22 05:27 UTC, Dallat65 commented on apps/client/src/pages/Dashboard/Groups/group/exploreGroupView/index.tsx
> +const cardData = [
Good job Rukky but pls note data wont come like this from the backend. Pls sync with backend guys.

2024-02-24 07:02 UTC, KristofaJosh commented on apps/client/src/pages/Dashboard/Groups/group/exploreGroupView/index.tsx
> +        </div> */}
needed?

2024-02-24 07:19 UTC, KristofaJosh commented
@pelzman using the table in this situation is fine.

although, 
- I have issues with the top section of the mobile view, it looks undone.

<img width="564" alt="image" src="https://github.com/Ajo-Savings-Project/ajo-savings/assets/48376769/116faa41-be46-45fc-904b-c5524e76ba3b">


- lastly, your breadcrumb is not interactive.

2024-02-24 07:20 UTC, KristofaJosh requested changes
Make research on breadcrumbs

2024-02-24 07:38 UTC, KristofaJosh submitted a review, later dismissed

2024-02-25 06:07 UTC, closed without merging