Cu 86bxc2ea2/explore group page
Ajo-Savings-Project/ajo-savings pull request #123
Opened 2024-02-19 15:19 UTC by Dallat65

Designed explore group page

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---
![Screen Shot 2024-02-19 at 16 13 11](https://github.com/Ajo-Savings-Project/ajo-savings/assets/131445852/fdd39bab-12c3-46a1-ab82-97eef51eedef)

![Screen Shot 2024-02-19 at 16 12 54](https://github.com/Ajo-Savings-Project/ajo-savings/assets/131445852/f37bf94c-01bd-4cd1-ad7a-eb44f684d3d6)

**How to test**  
_a brief message on how to test your changes, overwrite this or write "in ticket"_

2024-02-19 15:19 UTC, KristofaJosh commented
Task linked: [CU-86bxc2ea2 Explore group page](https://app.clickup.com/t/86bxc2ea2)

2024-02-19 22:19 UTC, KristofaJosh requested changes
Restructure your code and follow the our convention and best practices

2024-02-22 04:48 UTC, pelzman approved these changes
Good job, so far Daniel

but, you would have saved yourself the stress of writing this too long css by following the practise of MOBILE FIRST...
Learn to design for mobile first.....

2024-02-24 07:38 UTC, KristofaJosh approved these changes

2024-02-24 15:00 UTC, merged