feat:designed upcoming activites as a compound in dashboard home page
Ajo-Savings-Project/ajo-savings pull request #58
Opened 2023-12-11 16:58 UTC by Dallat65

Designed upcoming activities as a compound in dashboard home page
---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_
![Screen Shot 2023-12-11 at 17 57 24](https://github.com/Ajo-Savings-Project/ajo-savings/assets/131445852/7d83b5aa-42d9-4c3c-85d2-a705c86139f0)

---

**Test Coverage**  
_add relevant screenshots here_

2023-12-11 16:58 UTC, KristofaJosh commented
Task linked: [CU-86bwmckud Upcoming activities](https://app.clickup.com/t/86bwmckud)

2023-12-11 17:29 UTC, KristofaJosh requested changes

2023-12-15 09:11 UTC, KristofaJosh commented
> ![image](https://private-user-images.githubusercontent.com/107943338/290771712-34626c6d-5f98-4781-96c0-8f867752c92a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzE3MDksIm5iZiI6MTcwMjYzMTQwOSwicGF0aCI6Ii8xMDc5NDMzMzgvMjkwNzcxNzEyLTM0NjI2YzZkLTVmOTgtNDc4MS05NmMwLThmODY3NzUyYzkyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwOTEwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzliYjg3MWNhMDU4OGQ3N2M0OTE1MzBlMDM5YTNjNmZmNTM3OGJhMjhkZDNiZGJmNzVjZDk4MzlhY2Y0YzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CI_PgX7tS_rXPHJjuFi87mGDxMUDBm1KmW2mxe_e5cc) its better you use relative unit(rem) for your width, height, margin and padding to make it dynamic rather than pixel that makes it static

in this case, there's no problem.
- it's small, a smaller fontsize of the user browser (rem unit) will cause it to be smaller.

2023-12-15 09:11 UTC, KristofaJosh approved these changes

2023-12-16 20:24 UTC, pelzman submitted a review, later dismissed

2023-12-16 20:51 UTC, AnosikeChidinma submitted a review, later dismissed

2023-12-16 20:56 UTC, Dallat65 commented on apps/client/src/components/compounds/UpcomingActivities/UpcomingActivities.tsx
> +              <img src={img} alt={title} />
resolved

2023-12-19 08:32 UTC, merged