implemented user auth,user-login & documented with swagger while implementing reset password
Ajo-Savings-Project/ajo-savings pull request #68
Opened 2023-12-14 16:53 UTC by polymathmode

…ementing password reset

**Description of PR**

_A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange
feedback, and merge!_

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_

2023-12-14 16:53 UTC, KristofaJosh commented
Task linked: [CU-86bwj0ajy BE - Auth - Reset Password](https://app.clickup.com/t/86bwj0ajy)

2023-12-15 06:29 UTC, Jidekas commented on apps/server/src/controllers/userController.ts
> +      return res.status(400).json({
I think its best we use the error code variables declared in httpStatusCode.ts so that our codes will b uniform throughout. or what do you think?

2023-12-15 06:46 UTC, Jidekas commented on apps/server/src/controllers/userController.ts
> +      return res.status(400).json({ message: `User does not exist` })
i belive this should be 404 (user not found)

2023-12-15 07:30 UTC, Jidekas reviewed
- Your branch name is not named according to team convention.
- Also you didn't fill your PR description

2023-12-15 07:56 UTC, pelzman reviewed
Just address those changes highlighted by Akas, nice one.

2023-12-15 09:13 UTC, KristofaJosh commented
> * Your branch name is not named according to team convention.
> * Also you didn't fill your PR description

branch name is fine @Jidekas , since it's created from the ticket

2023-12-15 09:20 UTC, KristofaJosh commented on apps/server/src/controllers/userController.ts
> +//===================LOGIN-USER========================\\
No need for this, the user controller handles everything user and the function name matches the comment "login uer"

2023-12-15 12:08 UTC, KristofaJosh requested changes

2023-12-15 12:08 UTC, KristofaJosh commented
update this

export const HTTP_STATUS_CODE = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER: 500,
} as const

2023-12-17 00:30 UTC, KristofaJosh commented on apps/server/src/controllers/userController.ts
> +      method: req.method,
remove these... follow existing pattern

2023-12-17 00:31 UTC, KristofaJosh commented on apps/server/src/controllers/userController.ts
> +    })
we need to discuss how we intend maintaining user sessions

2023-12-17 00:32 UTC, KristofaJosh requested changes
Almost there.

2023-12-19 15:02 UTC, Jidekas approved these changes
Everything looks goog. All thats left is just the swagger docs for the token-refresh end point

2023-12-19 23:57 UTC, polymathmode commented
> Everything looks goog. All thats left is just the swagger docs for the token-refresh end point

That has now been handled!!

2023-12-20 07:44 UTC, KristofaJosh approved these changes

2023-12-20 21:57 UTC, closed without merging