Cu 86bwmcp3c/build my goal component
Ajo-Savings-Project/ajo-savings pull request #80
Opened 2023-12-20 08:40 UTC by Elyzsium

**Description of PR**

_A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange
feedback, and merge!_

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_

2023-12-20 08:41 UTC, KristofaJosh commented
Task linked: [CU-86bwmcp3c Build my goal component](https://app.clickup.com/t/86bwmcp3c)

2023-12-21 08:42 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +// Import statements
There's no need for this

2023-12-21 08:45 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +    target_amount: 10_000_000.0,
why did you this?

we should use numbers only

2023-12-21 08:48 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +        <span className={styles.headerText}>MY GOALS</span>
you can use the Typography element here

2023-12-21 08:49 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +        <Link to="/dashboard/savings" className={styles.view}>
use this instead:` routes.dashboard.savings.abs_path`

2023-12-21 08:57 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +    target_amount: 5_000_000.0,
use camelCase

2023-12-21 08:57 UTC, KristofaJosh commented on apps/client/src/components/compounds/goal/MyGoals.tsx
> +              )}
can be moved to a function

2023-12-21 09:02 UTC, KristofaJosh requested changes
Update your code accordingly

2023-12-22 10:48 UTC, KristofaJosh approved these changes
I believe we can improve the calculate percentage function

2023-12-25 03:11 UTC, AnosikeChidinma approved these changes

2023-12-25 13:17 UTC, Dallat65 commented
Welldone! Looks nice.

2023-12-25 13:17 UTC, Dallat65 approved these changes

2023-12-25 13:17 UTC, merged