Cu 86bwmczwm/total group savings endpoint
Ajo-Savings-Project/ajo-savings pull request #81
Opened 2023-12-20 13:02 UTC by Don-christo

**Description of PR**

_A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange
feedback, and merge!_

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_

2023-12-20 13:02 UTC, KristofaJosh commented
Task linked: [CU-86bwmczwm Total group savings endpoint](https://app.clickup.com/t/86bwmczwm)

2023-12-20 13:26 UTC, pelzman reviewed
Be consistent with the usage of the HTTP-Status-Code you imported...

Good job so far

2023-12-20 13:32 UTC, pelzman reviewed
You branch includes another commit(rechart type)  which is not yours and it shouldn't be so, since you didnt work on it .

2023-12-21 00:11 UTC, KristofaJosh requested changes
I don't think your code is rebased

2023-12-21 00:11 UTC, KristofaJosh commented on apps/client/package.json
>      "@vitejs/plugin-react-swc": "^3.5.0",
Your PR has changed here, why?

2023-12-21 00:11 UTC, KristofaJosh commented on apps/server/src/controllers/groupControllers/createGroup.ts
code can be improved

2023-12-22 14:23 UTC, KristofaJosh commented
Delete your local branch
check into this branch
make the fixes

- document your API
- test your code (currently not working)
- make any fixes and improvements
- update your PR description

2023-12-24 17:15 UTC, KristofaJosh approved these changes

2023-12-28 08:31 UTC, KristofaJosh commented
<img width="567" alt="image" src="https://github.com/Ajo-Savings-Project/ajo-savings/assets/48376769/b70aa32e-84f7-47d4-95c3-03cddfd5efba">

Update your documentation.
remove those highlighted values.

2023-12-30 06:32 UTC, Jidekas approved these changes
Everything works as intended. Though you could have stated something about the folder structure change in your PR description. makes it easy for the reviewer.
Great job!!

2023-12-30 12:31 UTC, merged