hero section added
Ajo-Savings-Project/ajo-savings pull request #9
Opened 2023-11-29 14:15 UTC by pelzman

**Description of PR**
designed the hero section of the landing page
A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange
feedback, and merge!

**Clickup Task**: [86bwj07gp][(https://app.clickup.com/t/86bwj07gp)]

---

Please check all that apply.

#### Checklist:

- [no ] Rebased with master
- [yes ] PR Description provided
- [yes ] Did you communicate these changes with the affected teams?
- [ no] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ no] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [yes ] Is this responsive and mobile friendly?
- [yes ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---
**Screenshots**  
_add relevant screenshots here_

---
**Test Coverage**  
_add relevant screenshots here_

2023-11-29 21:36 UTC, KristofaJosh requested changes
Your PR description needs improvement

2023-11-30 13:13 UTC, KristofaJosh commented
I have rebased your branc with main to resolve the conflicts, pull this branch and make your changes where necessary

accept all incoming

2023-12-01 06:43 UTC, Dallat65 approved these changes

2023-12-01 10:14 UTC, Afinjuomo approved these changes

2023-12-02 13:31 UTC, closed without merging