feat- designed transaction page
Ajo-Savings-Project/ajo-savings pull request #91
Opened 2024-01-08 20:27 UTC by Dallat65

**Description of PR**

designed transaction page to show today and yesterday's transaction details

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

---

**Test Coverage**  
_add relevant screenshots here_
![Screen Shot 2024-01-08 at 21 25 52](https://github.com/Ajo-Savings-Project/ajo-savings/assets/131445852/f452a6ae-7f0a-4bf2-95b3-11476cade793)

2024-01-08 20:27 UTC, KristofaJosh commented
Task linked: [CU-86bwt2tfa Transaction Page](https://app.clickup.com/t/86bwt2tfa)

2024-01-11 17:55 UTC, KristofaJosh requested changes

2024-01-11 17:55 UTC, KristofaJosh commented on apps/client/src/components/compounds/TransactionDetails/Image/UserImg.svg
we've discussed this earlier... no more using these images
use a placeholder instead like [lorempicsum](https://picsum.photos/200/300)

2024-01-11 17:55 UTC, KristofaJosh commented on apps/client/src/components/compounds/TransactionDetails/ResponsiveTable.tsx
> +                      <img src="https://picsum.photos/200/300" alt={row.name} />
the above causes you to miss out on styling this...

2024-01-11 17:55 UTC, KristofaJosh commented on apps/client/src/components/compounds/TransactionDetails/ResponsiveTable.tsx
Although, you didn't put a screenshot of the mobile view, I don't think this would look good on mobile

I'll advice you use grid to achieve this table

the idea https://www.youtube.com/watch?v=6Hw1HxHT_14

you can add this to your arsenal too https://www.youtube.com/watch?v=Ny7LkAt4btI

2024-01-11 17:56 UTC, KristofaJosh requested changes
Looks good but code can be greatly improved!

2024-02-07 10:50 UTC, Dallat65 commented
![Screen Shot 2024-02-07 at 11 46 06](https://github.com/Ajo-Savings-Project/ajo-savings/assets/131445852/10c09fe7-4fbb-4aef-a2ca-085374e6fd95)

2024-02-10 10:44 UTC, KristofaJosh commented
@Dallat65 I don't see a screenshot of your work

2024-02-13 07:45 UTC, KristofaJosh requested changes
You are close, but you implemented it wrongly.

UI is fine, you just have to fix your logic

2024-02-13 15:05 UTC, KristofaJosh commented
On mobile, you still didn't implement the grid I had asked you to do in the past

![image](https://github.com/Ajo-Savings-Project/ajo-savings/assets/48376769/70470517-6d2c-41df-bde0-55c5c6a5150e)

2024-02-17 06:15 UTC, pelzman submitted a review, later dismissed

2024-02-20 11:45 UTC, closed without merging